In [57]:
import numpy as np
import pandas as pd

In [58]:
from sklearn.model_selection import train_test_split

In [59]:
from sklearn.linear_model import LinearRegression

In [60]:
elantra = pd.read_csv("elantra.csv")

In [62]:
elantra.head()

Month  Year  ElantraSales  Unemployment  Queries  CPI_energy  CPI_all
0      1  2010          7690           9.7      153     213.377  217.466
1      1  2011          9659           9.1      259     229.353  221.082
2      1  2012         10900           8.2      354     244.178  227.666
3      1  2013         12174           7.9      230     242.560  231.321
4      1  2014         15326           6.6      232     247.575  234.933

In [63]:
elantra_train = elantra[elantra['Year'] <= 2012]

In [64]:
elantra_test = elantra[elantra['Year'] > 2012]

In [65]:
elantra_train.shape

(36, 7)

In [66]:
X_train = elantra_train[['Unemployment','Queries','CPI_energy','CPI_all']]

In [67]:
Y_train = elantra_train['ElantraSales']

In [68]:
model = LinearRegression()

In [69]:
model.fit(X_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [70]:
model.coef_

array([-3179.89957338,    19.02968262,    38.50603685,  -297.6456256 ])

In [71]:
model.intercept_

95385.36359709209

In [72]:
model.score(X_train,Y_train)

0.42815676686082826

In [73]:
model.coef_

array([-3179.89957338,    19.02968262,    38.50603685,  -297.6456256 ])

In [74]:
X_train_ms = elantra_train[['Month','Unemployment','Queries','CPI_energy','CPI_all']]

In [75]:
model1 = LinearRegression()

In [76]:
model1.fit(X_train_ms,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [77]:
model1.coef_

array([  110.68526965, -4137.28255887,    21.18551648,    54.18331666,
        -517.99103555])

In [78]:
model1.intercept_

148330.4876975611

In [79]:
model1.score(X_train_ms,Y_train)

0.4344443341223623

In [80]:
dummy = pd.get_dummies(X_train_ms['Month'])

In [81]:
df_train = pd.concat([X_train_ms,dummy],axis=1)

In [82]:
df_train.head()

Month  Unemployment  Queries  CPI_energy  CPI_all  1  2  3  4  5  6  7  8  \
0      1           9.7      153     213.377  217.466  1  0  0  0  0  0  0  0   
1      1           9.1      259     229.353  221.082  1  0  0  0  0  0  0  0   
2      1           8.2      354     244.178  227.666  1  0  0  0  0  0  0  0   
5      2           9.8      130     209.924  217.251  0  1  0  0  0  0  0  0   
6      2           9.0      266     232.188  221.816  0  1  0  0  0  0  0  0   

   9  10  11  12  
0  0   0   0   0  
1  0   0   0   0  
2  0   0   0   0  
5  0   0   0   0  
6  0   0   0   0

In [83]:
model2 = LinearRegression()

In [84]:
model2.fit(df_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [85]:
model2.coef_

array([ 9.46820616e+01, -7.73938143e+03, -4.76364625e+00,  2.88631413e+02,
       -1.34330683e+03, -5.06753767e+03, -2.90722192e+03,  1.43965497e+03,
        2.20502353e+03,  1.97398308e+03,  3.67488463e+03,  4.29383439e+03,
        2.20913534e+03, -8.11707509e+02, -3.41949247e+03, -2.77542678e+03,
       -8.15129609e+02])

In [86]:
model2.intercept_

317482.1357863353

In [87]:
model2.score(df_train,Y_train)

0.8192642006018227

In [88]:
elantra_train['Queries'].corr(elantra_train['Month'])

0.015844295874459076

In [89]:
elantra_train['Queries'].corr(elantra_train['Unemployment'])

-0.6411092910339306

In [90]:
elantra_train['Queries'].corr(elantra_train['CPI_energy'])

0.832838105860978

In [91]:
elantra_train['Queries'].corr(elantra_train['CPI_all'])

0.7536732362501505

In [92]:
elantra_test.ElantraSales.mean()

19973.64285714286

In [93]:
X_train_10 = elantra_train.drop(['Queries','ElantraSales'],axis=1)

In [94]:
X_train_10 = pd.concat([X_train_10,(pd.get_dummies(X_train_10['Month']))], axis = 1)

In [95]:
X_train_10['Years'] = pd.Categorical(X_train_10['Year'])

In [96]:
X_train_10 = X_train_10.drop(['Month','Year'],axis=1)

In [97]:
X_test_10 = elantra_test.drop(['Queries','ElantraSales'],axis=1)

In [98]:
X_test_10 = pd.concat([X_test_10,(pd.get_dummies(X_test_10['Month']))], axis = 1)

In [99]:
X_test_10['Years'] = pd.Categorical(X_test_10['Year'])

In [100]:
X_test_10  = X_test_10.drop(['Month','Year'],axis=1)

In [101]:
Y_train_10 = elantra_train['ElantraSales']
Y_test_10 = elantra_test['ElantraSales']

In [102]:
model_10 = LinearRegression()

In [103]:
model_10.fit(X_train_10,Y_train_10)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [104]:
y_pred_test_10 = model_10.predict(X_test_10)

In [105]:
model_10.score(X_test_10,Y_test_10)

0.5538700156585167

In [106]:
from sklearn.metrics import mean_squared_error

In [107]:
test_rmse_10 = np.sqrt(mean_squared_error(Y_test_10,y_pred_test_10))

In [109]:
test_rmse_10

2966.2974416077077

In [110]:
Sum=0
for i,j in zip(Y_test_10,y_pred_test_10):
    sq = (i - j) ** 2
    Sum = Sum + sq

In [111]:
Sum

123184887.16923806

In [113]:
y_bar = Y_test_10.mean()

In [115]:
Summation = 0 
for i in Y_test_10:
    square = (i - y_bar) ** 2
    Summation = Summation + square


In [116]:
Summation

276118825.21428573

In [118]:
r_sq_score_10 = 1 - (Sum/Summation)

In [119]:
r_sq_score_10

0.5538700156585167